<?php

namespace Database\Seeders;
use Carbon\Carbon;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Hash;
use Illuminate\Database\Seeder;

class DatabaseSeeder extends Seeder
{
    /**
     * Seed the application's database.
     *
     * @return void
     */
    public function run()
    {
         DB::table('users')->insert([
            [
            'name' => 'admin',
            'email' => 'admin@gmail.com',
            'password' => Hash::make('12345'),
            'phone' => '0392096959',
            'role'=>'1',
            'created_at' => Carbon :: now()->format('Y-m-d H:i:s'),
            'updated_at' => Carbon :: now()->format('Y-m-d H:i:s'),

            ],
             [
            'name' => 'Nguyễn Quỳnh Vy Vy',
            'email' => 'vy@gmail.com',
            'password' => Hash::make('12345'),
            'phone' => '0392096958',
            'role'=>'1',
            'created_at' => Carbon :: now()->format('Y-m-d H:i:s'),
            'updated_at' => Carbon :: now()->format('Y-m-d H:i:s'),

            ],
             [
            'name' => 'Lâm Thanh Khang',
            'email' => 'Khang@gmail.com',
            'password' => Hash::make('12345'),
            'phone' => '0392096957',
            'role'=>'1',
            'created_at' => Carbon :: now()->format('Y-m-d H:i:s'),
            'updated_at' => Carbon :: now()->format('Y-m-d H:i:s'),

            ],
             [
            'name' => 'Nguyễn Trung Hậu',
            'email' => 'hậu@gmail.com',
            'password' => Hash::make('12345'),
            'phone' => '0392096956',
            'role'=>'1',
            'created_at' => Carbon :: now()->format('Y-m-d H:i:s'),
            'updated_at' => Carbon :: now()->format('Y-m-d H:i:s'),

            ],
            [
            'name' => 'Nguyễn Khánh Linh',
            'email' => 'nklinh1@gmail.com',
            'password' => Hash::make('123456'),
            'phone' => '0392096968',
            'rolr'=> '0',
            'created_at' => Carbon :: now()->format('Y-m-d H:i:s'),
            'updated_at' => Carbon :: now()->format('Y-m-d H:i:s'),
           ] ,
        ]);
         DB::table('products')->insert([
             [
                 'product_name' => 'Thuốc Dopolys-S Domesco Trị Suy Tĩnh Mạch Bạch Huyết (Hộp 3 Vỉ X 10 Viên)',
                 'category_id' => '1',
                 'product_desc' => 'Dopolys-S có thành phần chính Ginkgo biloba extract 7 mg, Heptaminol hydrochlorid 150 mg, Troxerutin 150 mg để điều trị triệu chứng suy tĩnh mạch bạch huyết: Nặng chân, vọp bẻ, đau nhức, hội chứng cẳng chân rung khi nằm, điều trị những dấu hiệu chức năng có liên quan đến cơn trĩ cấp.',
                 'product_price' => '100000',
                 'product_image' => 'dopolys.jpg',
                 'qty' => '50',
                 'created_at' => Carbon :: now()->format('Y-m-d H:i:s'),
                 'updated_at' => Carbon :: now()->format('Y-m-d H:i:s'),
             ],
              [
                 'product_name' => 'Thuốc Clopidogrel 75Mg Mv Phòng Nhồi Máu Cơ Tim, Đột Quỵ',
                 'category_id' => '1',
                 'product_desc' => 'Thuốc Clopidogrel 75 Mv dạng viên nén bao phim của Công ty TNHH US Pharma USA - Việt Nam có thành phần chính là Clopidogrel (dưới dạng Clopidogrel Bisulfat) 75mg là loại thuốc được chỉ định sử dụng để phòng ngừa cơn nhồi máu cơ tim và đột quỵ ở những người có bệnh tim (bị nhồi máu cơ tim gần đây), đột quỵ gần đây, hoặc bệnh tuần hoàn máu (bệnh mạch máu ngoại biên). Thuốc cũng được sử dụng chung với Aspirin để điều trị các cơn đau ngực gần đây hoặc cơn đau trở nặng hơn (đau tim, đau thắt ngực không ổn định), giữ cho các mạch máu giãn tốt và ngăn ngừa cục máu đông sau những can thiệp y tế nhất định (chẳng hạn như thông tim/nong mạch vành).',
                 'product_price' => '120000',
                 'product_image' => 'clopidogrel.jpg',
                 'qty' => '50',
                 'created_at' => Carbon :: now()->format('Y-m-d H:i:s'),
                 'updated_at' => Carbon :: now()->format('Y-m-d H:i:s'),
             ],
                [
                 'product_name' => 'Thuốc Cardilopin 5Mg Trị Tăng Huyết Áp (Hộp 3 Vỉ X 10 Viên)',
                 'category_id' => '1',
                 'product_desc' => 'Cardilopin 5 do công ty Egis Pharmaceuticals PLC (Hungary) sản xuất, thành phần chính amlodipine, là thuốc dùng để điều trị tăng huyết áp; dùng đơn thuần hay phối hợp với các thuốc hạ huyết áp khác. Cardilopin 5 còn điều trị chứng đau thắt ngực ổn định và đau thắt ngực do co thắt mạch (đau thắt ngực Prinzmetal), dùng đơn thuần hay phối hợp với các thuốc chống đau thắt ngực khác.',
                 'product_price' => '120000',
                 'product_image' => 'cardilopin.jpg',
                 'qty' => '40',
                 'created_at' => Carbon :: now()->format('Y-m-d H:i:s'),
                 'updated_at' => Carbon :: now()->format('Y-m-d H:i:s'),
             ],
              [
                 'product_name' => 'Hoạt Huyết Dưỡng Não Cerecaps Cải Thiện Suy Giảm Trí Nhớ, Chóng Mặt',
                 'category_id' => '1',
                 'product_desc' => 'Thuốc Hoạt Huyết Dưỡng Não Cerecaps là dược phẩm của Công ty Cổ phần Dược Trung Ương Mediplantex, có thành phần chính cao khô hỗn hợp các dược liệu, giúp điều trị hiệu quả các trường hợp như: Suy giảm trí nhớ, đau đầu, hoa mắt chóng mặt, hay cáu gắt ở người có tuổi, thiếu máu, căng thẳng, mệt mỏi, mất tập trung, chứng tê bì, nhức mỏi chân tay (do thiểu năng tuần hoàn ngoại vi)...',
                 'product_price' => '71000',
                 'product_image' => 'cerecaps.jpg',
                 'qty' => '30',
                 'created_at' => Carbon :: now()->format('Y-m-d H:i:s'),
                 'updated_at' => Carbon :: now()->format('Y-m-d H:i:s'),
             ],
             [
                 'product_name' => 'Amlodipin 5Mg Trị Tăng Huyết Áp, Đau Thắt Ngực Ổn Định',
                 'category_id' => '1',
                 'product_desc' => 'Amlodipin 5mg của Công ty cổ phần dược phẩm Trường Thọ, thành phần chính là amlodipin. Amlodipin 5mg là thuốc điều trị tăng huyết áp, đau thắt ngực ổn định, đau thắt ngực kiểu Prinzmetal. Amlodipin 5mg được bào chế dưới dạng viên nén, đóng gói theo quy cách hộp 3 vỉ x 10 viên.',
                 'product_price' => '146000',
                 'product_image' => 'amlodipin.jpg',
                 'qty' => '30',
                 'created_at' => Carbon :: now()->format('Y-m-d H:i:s'),
                 'updated_at' => Carbon :: now()->format('Y-m-d H:i:s'),
             ],
             [
                 'product_name' => 'Viên Ngậm Strepsils Throat Irritation Cough Tan Đàm, Làm Sạch Đường Thở',
                 'category_id' => '1',
                 'product_desc' => 'Thuốc Strepsils Throat Irritation Cough là sản phẩm của Công ty Reckitt Benckiser Healthcare Manufacturing (Thailand) có chứa Ambroxol Hydrochlorid với công dụng giúp làm sạch đường thở và kiểm soát ho do phổi gây ra bởi chất nhầy dầy đặc. Viên ngậm hình tròn, màu vàng cam, có mùi cam đặc trưng.',
                 'product_price' => '51000',
                 'product_image' => 'strepsils.jpg',
                 'qty' => '50',
                 'created_at' => Carbon :: now()->format('Y-m-d H:i:s'),
                 'updated_at' => Carbon :: now()->format('Y-m-d H:i:s'),
             ],
             [
                 'product_name' => 'Thuốc Vigentin 500Mg/62.5Mg Trị Nhiễm Khuẩn Đường Hô Hấp',
                 'category_id' => '1',
                 'product_desc' => 'Thuốc Vigentin 500mg/62.5mg là sản phẩm của Công ty Cổ phần Dược phẩm Trung ương - Pharbaco, thành phần chính amoxicillin và acid clavulanic, là thuốc dùng để điều trị trong thời gian ngắn các trường hợp nhiễm khuẩn sau: Nhiễm khuẩn đường hô hấp trên, nhiễm khuẩn đường hô hấp dưới, nhiễm khuẩn nặng đường tiết niệu - sinh dục bởi các chủng, nhiễm khuẩn da và mô mềm, nhiễm khuẩn xương và khớp, nhiễm khuẩn nha khoa, nhiễm khuẩn do nạo thai. Thuốc được bào chế dưới dạng thuốc bột pha hỗn dịch uống, bột thuốc màu trắng ngà hoặc hơi vàng, tơi xốp, không dính tay, vị ngọt, mùi thơm đặc trưng dễ chịu đóng gói trong túi giấy/nhôm/polyethylen hàn kín.',
                 'product_price' => '200000',
                 'product_image' => 'vigentin.jpg',
                 'qty' => '50',
                 'created_at' => Carbon :: now()->format('Y-m-d H:i:s'),
                 'updated_at' => Carbon :: now()->format('Y-m-d H:i:s'),
             ],
             [
                 'product_name' => 'Thuốc Fefasdin 60 Khapharco Trị Viêm Mũi Dị Ứng Theo Mùa',
                 'category_id' => '1',
                 'product_desc' => 'Thuốc FEFASDIN 60 do Công ty Cổ phần Dược phẩm Khánh Hòa sản xuất có chứa Fexofenadin hydroclorid 60 mg với công dụng điều trị triệu chứng viêm mũi dị ứng theo mùa, mày đay mạn tính vô căn ở người lớn và trẻ em trên 6 tuổi. Viên nén bao phim màu hồng, một mặt có gạch ngang, một mặt có chữ KPC được dập trực tiếp trên mặt viên, cạnh và thành viên lành lặn.',
                 'product_price' => '120000',
                 'product_image' => 'fefasdin.jpg',
                 'qty' => '50',
                 'created_at' => Carbon :: now()->format('Y-m-d H:i:s'),
                 'updated_at' => Carbon :: now()->format('Y-m-d H:i:s'),
             ],
             [
                 'product_name' => 'Thuốc Bột Glucosamine 1500Mg Stada Sachet 30 Gói',
                 'category_id' => '1',
                 'product_desc' => 'Thuốc bột Glucosamine là sản phẩm của Stada Arzneimittel AG - Đức có thành phần chính là Glucosamine sulfate có tác dụng giảm triệu chứng của thoái hóa khớp gối nhẹ và trung bình.',
                 'product_price' => '130000',
                 'product_image' => 'glucosamine.jpg',
                 'qty' => '50',
                 'created_at' => Carbon :: now()->format('Y-m-d H:i:s'),
                 'updated_at' => Carbon :: now()->format('Y-m-d H:i:s'),
             ],
             [
                 'product_name' => 'Thuốc Pokemine Medisun Bổ Sung Sắt ( 20 Ống X 10Ml)',
                 'category_id' => '1',
                 'product_desc' => 'Pokemine do Công ty Cổ Phần Dược Phẩm MEDISUN có chứa Sắt nguyên tố (dưới dạng phức hợp sắt III hydroxid polymaltose) 50 mg dạng dung dịch uống 10 ml với công dụng bổ sung sắt cho bệnh nhân có nguy cơ bị thiếu máu do thiếu sắt như: Phụ nữ mang thai, phụ nữ cho con bú, người suy dinh dưỡng, người bệnh sau phẫu thuật, trẻ em thiếu máu do thiếu sắt, chậm lớn, còi cọc.',
                 'product_price' => '120000',
                 'product_image' => 'pokemine.jpg',
                 'qty' => '50',
                 'created_at' => Carbon :: now()->format('Y-m-d H:i:s'),
                 'updated_at' => Carbon :: now()->format('Y-m-d H:i:s'),
             ],
             [
                 'product_name' => 'Calcium Corbiere Extra 5Ml Sanofi Bổ Sung Canxi Cho Trẻ Em',
                 'category_id' => '1',
                 'product_desc' => 'Dung dịch uống Calcium Corbiere Kids Extra 5ml là sản phẩm của Dược phẩm Sanofi có thành phần chính gồm Calcium Glubionate và Calcium Lactobionate dùng trong trường hợp bổ sung canxi có nhu cầu canxi cao như: Phụ nữ mang thai và cho con bú, trẻ em đang lớn,giai đoạn hồi phục, gãy xương, chứng còi xương và hỗ trợ điều trị loãng xương.',
                 'product_price' => '150000',
                 'product_image' => 'calcium.jpg',
                 'qty' => '50',
                 'created_at' => Carbon :: now()->format('Y-m-d H:i:s'),
                 'updated_at' => Carbon :: now()->format('Y-m-d H:i:s'),
             ],
             [
                 'product_name' => 'Thuốc Mydocalm 150Mg Trị Sự Tăng Trương Lực Cơ Xương',
                 'category_id' => '1',
                 'product_desc' => 'Thuốc Mydocalm 150mg là dược phẩm của Gedeon Richter., Ltd - HUNG GA RY, có thành phần chính hoạt chất tolperison hydrochlorid 150mg. Thuốc được chỉ định điều trị sự tăng trương lực cơ xương trong các rối loạn thần kinh thực thể; tăng trương lực cơ, co thắt cơ và các co thắt kèm theo các bệnh vận động; phục hồi chức năng sau các phẫu thuật chấn thương - chỉnh hình; điều trị các bệnh nghẽn mạch cũng như những hội chứng xuất hiện trên cơ sở suy giảm sự phân bố thần kinh - mạch.',
                 'product_price' => '230000',
                 'product_image' => 'mydocalm.jpg',
                 'qty' => '50',
                 'created_at' => Carbon :: now()->format('Y-m-d H:i:s'),
                 'updated_at' => Carbon :: now()->format('Y-m-d H:i:s'),
             ],
              [
                 'product_name' => 'Viên Uống Làm Đẹp Da Perfect White Jpanwell 60 Viên',
                 'category_id' => '2',
                 'product_desc' => 'Làn da căng mịn, hồng hào tự nhiên là chìa khóa cho nét đẹp vĩnh cửu mà mọi cô gái đều mong muốn sở hữu. Đó cũng chính là bí quyết mà những nhà làm đẹp Nhật Bản luôn theo đuổi nghiên cứu để hóa phép thần kỳ cho làn da phụ nữ, tạo nên chuẩn mực của nét đẹp hiện đại - làn da đầy sinh khí, rạng ngời không tì vết.',
                 'product_price' => '1230000',
                 'product_image' => 'perfect-ưhite.jpg',
                 'qty' => '50',
                 'created_at' => Carbon :: now()->format('Y-m-d H:i:s'),
                 'updated_at' => Carbon :: now()->format('Y-m-d H:i:s'),
             ],
             [
                 'product_name' => 'Viên Uống Hỗ Trợ Chống Oxy Hóa Glutasi Glutathione',
                 'category_id' => '2',
                 'product_desc' => 'Glutathione ngăn chặn sự hình thành và sản sinh các hắc sắc tố melanin, nguyên nhân gây nên tình trạng sạm da, nám da. Glutathione còn giúp tăng cường sản sinh các sắc tố làm hồng trắng da, giúp mang lại cho bạn một làn da trắng hồng, giàu sức sống, tăng cường sự đàn hồi và làm mịn da, giúp trị nám da, tàn nhang, ngừa lão hóa da hiệu quả. Glutathione còn giúp phục hồi chức năng gan. Đặc biệt glutathione dùng trước khi trị xạ giúp bảo vệ tế bào khỏi sự tổn thương do bức xạ ion hóa, làm chậm tiến triển của bệnh AIDS. Nói cách khác Glutathione có thể giúp bạn giải độc cơ thể và hoạt động như một lá chắn bảo vệ.',
                 'product_price' => '800000',
                 'product_image' => 'glutasi-phytextra.jpg',
                 'qty' => '50',
                 'created_at' => Carbon :: now()->format('Y-m-d H:i:s'),
                 'updated_at' => Carbon :: now()->format('Y-m-d H:i:s'),
             ],
             [
                 'product_name' => 'Viên Uống Giảm Sạm Nám Skin Care Pigment Clear New Nordic 60 Viên',
                 'category_id' => '2',
                 'product_desc' => 'Skin Care Pigment Clear từ Thụy Điển bổ sung chất dinh dưỡng phục vụ cho các chức năng quan trọng của da. Nuôi dưỡng làn da khỏe mạnh, trắng sáng từ bên trong, cải thiện sạm, nám, tàn nhang và hỗ trợ chống oxy hóa, giữ gìn vẻ tươi tắn của làn da.',
                 'product_price' => '850000',
                 'product_image' => 'skin-care.jpg',
                 'qty' => '50',
                 'created_at' => Carbon :: now()->format('Y-m-d H:i:s'),
                 'updated_at' => Carbon :: now()->format('Y-m-d H:i:s'),
             ],
              [
                 'product_name' => 'Đông Trùng Hạ Thảo Kotimogin (Hộp 20 vỉ x 3 viên)',
                 'category_id' => '2',
                 'product_desc' => 'Đông trùng hạ thảo có vị ngọt, tính ôn vào hai kênh phế và thận, có tác dụng bồi bổ cơ thể cho người ốm, ích phế, bổ thận, bổ tinh tủy, cầm máu, hóa đờm, dùng chữa hư hao sinh ho, ho ra máu, liệt dương, lưng đau mỏi gối, di tinh, đau tim.',
                 'product_price' => '330000',
                 'product_image' => 'dong-trung-ha-thao-kotimogin.jpg',
                 'qty' => '50',
                 'created_at' => Carbon :: now()->format('Y-m-d H:i:s'),
                 'updated_at' => Carbon :: now()->format('Y-m-d H:i:s'),
             ],
              [
                 'product_name' => 'Viên Uống Giúp Ngủ Ngon Trùng Thảo Gold Thành Công 30 Viên',
                 'category_id' => '2',
                 'product_desc' => 'Giấc ngủ rất quan trọng đối với cơ thể. Khi ngủ, các cơ quan sẽ được phục hồi năng lượng sau một ngày làm việc mệt mỏi, tái sinh các tế bào não và chuẩn bị ‘nhiên liệu’ cho những hoạt động tiếp theo trong ngày mới. Thiếu ngủ chính là vấn đề nghiêm trọng gây suy nhược cơ thể, căng thẳng thần kinh, đầu óc thiếu tỉnh táo, ăn uống kém và dẫn đến nhiều hệ lụy sức khỏe khác. ',
                 'product_price' => '1230000',
                 'product_image' => 'trung-thao.jpg',
                 'qty' => '50',
                 'created_at' => Carbon :: now()->format('Y-m-d H:i:s'),
                 'updated_at' => Carbon :: now()->format('Y-m-d H:i:s'),
             ],
              [
                 'product_name' => 'Viên Uống Bổ Khớp Plus Min New Phytextra 100 Viên',
                 'category_id' => '2',
                 'product_desc' => 'Quan tâm đến xương khớp là cách để bạn có được cơ thể vững vàng, PLus Min New sẽ cùng bạn chăm sóc xương khớp khỏe mạnh và linh hoạt. PLus Min New tổng hợp các thành phần quan trọng nhất tốt cho quá trình tái tạo mô sụn khớp, nâng cao sức khỏe của hệ xương khớp và bảo vệ khớp tối ưu trong suốt quá trình vận động phục vụ cho cuộc sống của bạn.',
                 'product_price' => '609000',
                 'product_image' => 'phytextra.jpg',
                 'qty' => '50',
                 'created_at' => Carbon :: now()->format('Y-m-d H:i:s'),
                 'updated_at' => Carbon :: now()->format('Y-m-d H:i:s'),
             ],
              [
                 'product_name' => 'Viên Uống Bổ Sung Canxi Anica Phytextra Ngừa Loãng Xương, Còi Xương',
                 'category_id' => '2',
                 'product_desc' => 'Chứa nguồn canxi, vitamin D3 và vitamin K2 dồi dào, Anica giúp tăng cường sức khỏe hệ cơ xương, hỗ trợ tăng chiều cao tối đa cho trẻ em và thanh thiếu niên, cải thiện tình trạng đau nhức xương khớp ở người cao tuổi.',
                 'product_price' => '5130000',
                 'product_image' => 'anica.jpg',
                 'qty' => '50',
                 'created_at' => Carbon :: now()->format('Y-m-d H:i:s'),
                 'updated_at' => Carbon :: now()->format('Y-m-d H:i:s'),
             ],
              [
                 'product_name' => 'Viên Uống Bổ Sung Canxi Omexxel Calk2 Excelife 30 Viên',
                 'category_id' => '2',
                 'product_desc' => 'Omexxel Calk2 với công thức đặc biệt cung cấp các chất cần thiết cho quá trình tạo xương gồm: Calcium, Vitamin D3, Vitamin K2 và Omega 3. Đồng thời hỗ trợ giảm xơ vữa động mạch và nguy cơ mắc các bệnh tim mạch.',
                 'product_price' => '330000',
                 'product_image' => 'omexxel.jpg',
                 'qty' => '50',
                 'created_at' => Carbon :: now()->format('Y-m-d H:i:s'),
                 'updated_at' => Carbon :: now()->format('Y-m-d H:i:s'),
             ],
             [
                 'product_name' => 'Khẩu Trang Hamita N95 Medical Face Mask',
                 'category_id' => '3',
                 'product_desc' => 'Khẩu Trang Hamita N95 Hộp 10 Cái với lớp lọc khuẩn công nghệ tĩnh điện để giữ lại các hạt mịn ô nhiễm không khí hiệu quả: Trên 95% bụi mịn 0.3 micron và trên 98% bụi mịn &lt; 2.5 micron. Đây là khẩu trang y tế chủng loại N95 được khuyến nghị sử dụng khi chỉ số chất lượng không khí trên 100 (AQI).',
                 'product_price' => '65000',
                 'product_image' => 'khautranghamita.jpg',
                 'qty' => '50',
                 'created_at' => Carbon :: now()->format('Y-m-d H:i:s'),
                 'updated_at' => Carbon :: now()->format('Y-m-d H:i:s'),
             ],
           [
                 'product_name' => 'Khẩu Trang Y Tế Cao Cấp Vĩnh Tiến Kn95',
                 'category_id' => '3',
                 'product_desc' => 'Khẩu Trang Y Tế Cao Cấp Vĩnh Tiến Kn95 3Hmask 12C được sản xuất bằng công nghệ hiện đại, kháng khuẩn đến 99%, dễ dàng hít thở và không gây dị ứng cho người sử dụng.',
                 'product_price' => '79000',
                 'product_image' => 'khau-trang-y-te-cao-cap-vinh-tien-kn95.jpg',
                 'qty' => '50',
                 'created_at' => Carbon :: now()->format('Y-m-d H:i:s'),
                 'updated_at' => Carbon :: now()->format('Y-m-d H:i:s'),
             ], 
              [
                 'product_name' => 'Khẩu Trang Y Tế Người Lớn Hamita Advanced 4D Mask (Gói 5 Cái)',
                 'category_id' => '3',
                 'product_desc' => 'Khẩu trang y tế người lớn Hamita Advanced 4D Mask có khả năng bảo vệ chống nhiễm khuẩn đến 99.60%, thiết kế 4D thông minh ôm khít khuôn mặt, giúp bảo vệ hiệu quả khỏi khói bụi ô nhiễm, chống giọt bắn và vi khuẩn từ môi trường.',
                 'product_price' => '40000',
                 'product_image' => '00030973-khau-trang-y-te-nguoi-lon-hamita-advanced-4d-mask-goi-5-cai-4771-60b4_large.jpg',
                 'qty' => '50',
                 'created_at' => Carbon :: now()->format('Y-m-d H:i:s'),
                 'updated_at' => Carbon :: now()->format('Y-m-d H:i:s'),
             ], 
             [
                 'product_name' => 'Nhiệt Kế Đầu Mềm Beurer Ft15',
                 'category_id' => '3',
                 'product_desc' => 'Nhiệt Kế Đầu Mềm Beurer Ft15 giúp đo nhiệt độ nhanh trong khoảng 10 giây, đầu đo mềm, linh hoạt, an toàn với trẻ nhỏ. Thiết bị có các chức năng nổi bật như: Phát tín hiệu âm thanh báo kết quả đo, cảnh báo sốt, tự động tắt, không thấm nước,...',
                 'product_price' => '165000',
                 'product_image' => '00031819-nhiet-ke-dau-mem-beurer-ft15-5365-6114_large.jpg',
                 'qty' => '50',
                 'created_at' => Carbon :: now()->format('Y-m-d H:i:s'),
                 'updated_at' => Carbon :: now()->format('Y-m-d H:i:s'),
             ], 
              [
                 'product_name' => 'Kem Đánh Răng Lipzo Gum Protect 95G',
                 'category_id' => '4',
                 'product_desc' => ' Lipzo Gum Protect là sự kết hợp giữa Xylitol, tính chất muối biển, keo ong, thảo dược cây xô thơm và quả ổi, sản phẩm giúp kháng khuẩn tự nhiên, ngăn ngừa chảy máu chân răng, đặc biệt ngăn ngừa tụt nướu và phục hồi chân nướu săn chắc cho nụ cười bạn không chỉ đẹp mà còn khỏe từ bên trong.',
                 'product_price' => '65000',
                 'product_image' => '00029554-kem-danh-rang-lipzo-gum-protect-95g-2021-600a_large.jpg',
                 'qty' => '50',
                 'created_at' => Carbon :: now()->format('Y-m-d H:i:s'),
                 'updated_at' => Carbon :: now()->format('Y-m-d H:i:s'),
             ],
             [
                 'product_name' => 'Nước Hồng Sâm Hongsamjin Plus 15 Gói X 70Ml',
                 'category_id' => '4',
                 'product_desc' => 'Nước Hồng Sâm Hongsamjin Plus là sản phẩm kết hợp các thành phần cao cấp, quý hiếm như chiết xuất Hồng sâm Hàn Quốc 6 năm tuổi, Gạc Hươu, Linh Chi, Nhung Hươu, Táo đỏ và Câu Kỷ Tử mang đến giá trị dinh dưỡng tuyệt vời trong dạng túi độc đáo, hiện đại, tiện lợi. Sử dụng sản phẩm giúp bổ sung dinh dưỡng, tăng cường sức khỏe và sức đề kháng cho người dùng.',
                 'product_price' => '490000',
                 'product_image' => '00033432-nuoc-hong-sam-hongsamjin-plus-15-goi-x-70ml-6712-6214_large.jpg',
                 'qty' => '10',
                 'created_at' => Carbon :: now()->format('Y-m-d H:i:s'),
                 'updated_at' => Carbon :: now()->format('Y-m-d H:i:s'),
             ],
             [
                 'product_name' => 'Viên Tinh Nghệ Mật Ong Sữa Chúa Honeyland Tốt Cho Sức Khỏe 120G',
                 'category_id' => '4',
                 'product_desc' => 'Viên tinh nghệ mật sữa chúa là sự kết hợp hoàn hảo của sữa ong chúa tươi, mật ong và tinh nghệ Curcumin tạo ra 1 sản phẩm chất lượng có mùi vị thơm ngon, tiện lợi khi sử dụng và tốt cho sức khỏe.',
                 'product_price' => '196000',
                 'product_image' => '00033624-vien-tinh-nghe-mat-ong-sua-chua-honeyland-120g-2289-6233_large.jpg',
                 'qty' => '10',
                 'created_at' => Carbon :: now()->format('Y-m-d H:i:s'),
                 'updated_at' => Carbon :: now()->format('Y-m-d H:i:s'),
             ],
              [
                 'product_name' => 'Nước Xịt Khuẩn Tay Natural Hand Sanitizer 500Ml',
                 'category_id' => '4',
                 'product_desc' => 'Dung dịch rửa tay khô Natural Hand Sanitizer là sản phẩm giúp làm sạch và loại bỏ hầu hết vi khuẩn gây hại trên da tay mà không cần rửa lại bằng nước, giúp bảo vệ sức khỏe nhưng vẫn giữ cho tay bạn luôn mềm mại, dễ chịu. Ngoài ra, sản phẩm với hương thơm trà xanh và sả chanh dễ chịu, giúp khử mùi cho đôi tay hiệu quả',
                 'product_price' => '16000',
                 'product_image' => '00032957-dung-dich-rua-tay-kho-natural-hand-sanitizer-500ml-4459-61af_large.jpg',
                 'qty' => '10',
                 'created_at' => Carbon :: now()->format('Y-m-d H:i:s'),
                 'updated_at' => Carbon :: now()->format('Y-m-d H:i:s'),
             ],
              [
                 'product_name' => 'Kem Đánh Răng Dental Sensitive Whitening - Trắng Răng Cho Răng Nhạy Cảm - 100Ml',
                 'category_id' => '4',
                 'product_desc' => 'Kem đánh răng Dental Sensitive Whitening Formula giúp cải thiện tình trạng ê buốt, nhẹ nhàng tạo nên lớp bảo vệ tự nhiên, giúp răng ngày một chắc khỏe và trắng sáng hơn.',
                 'product_price' => '99000',
                 'product_image' => '00028946-kem-danh-rang-dental-sensitive-whitening-trang-rang-cho-rang-nhay-cam-100ml-7383-5fd0_large.jpg',
                 'qty' => '10',
                 'created_at' => Carbon :: now()->format('Y-m-d H:i:s'),
                 'updated_at' => Carbon :: now()->format('Y-m-d H:i:s'),
             ],

         ]);
         DB::table('product_category')->insert([
            [
                'category_id' =>'1',
                'category_name' =>'Thuốc',
                'created_at'=>Carbon :: now()->format('Y-m-d H:i:s'),
                'created_at'=>Carbon :: now()->format('Y-m-d H:i:s'),
            ],
             [
                'category_id' =>'2',
                'category_name' =>'Thực phẩm chức năng',
                'created_at'=>Carbon :: now()->format('Y-m-d H:i:s'),
                'created_at'=>Carbon :: now()->format('Y-m-d H:i:s'),
            ],
             [
                'category_id' =>'3',
                'category_name' =>'Thiết Bị Y Tế',
                'created_at'=>Carbon :: now()->format('Y-m-d H:i:s'),
                'created_at'=>Carbon :: now()->format('Y-m-d H:i:s'),
            ],
            [
                'category_id' =>'4',
                'category_name' =>'Chăm Sóc Cá Nhân',
                'created_at'=>Carbon :: now()->format('Y-m-d H:i:s'),
                'created_at'=>Carbon :: now()->format('Y-m-d H:i:s'),
            ],
            
         ]);
         DB::table('products_detail')->insert([
            [
                'product_id'=>'1',
                'category_name'=>'Thành Phần Chính',
                'product_desc'=>'Bạch quả, Troxerutin, Heptaminol',
                'created_at'=>Carbon :: now()->format('Y-m-d H:i:s'),
                'created_at'=>Carbon :: now()->format('Y-m-d H:i:s'),
            ],
            [   
                'product_id'=>'1',
                'category_name'=>'Quy Cách',
                'product_desc'=>'Hộp 3 vỉ x 10 viên',
                'created_at'=>Carbon :: now()->format('Y-m-d H:i:s'),
                'created_at'=>Carbon :: now()->format('Y-m-d H:i:s'),
            ],
            [
                'product_id'=>'1',
                'category_name'=>'Xuất Xứ Thương Hiệu',
                'product_desc'=>'Việt Nam',
                'created_at'=>Carbon :: now()->format('Y-m-d H:i:s'),
                'created_at'=>Carbon :: now()->format('Y-m-d H:i:s'),
            ],
            [
                'product_id'=>'1',
                'category_name'=>'Dạng bào chế',
                'product_desc'=>'Viên nan cứng',
                'created_at'=>Carbon :: now()->format('Y-m-d H:i:s'),
                'created_at'=>Carbon :: now()->format('Y-m-d H:i:s'),
            ],
            [
                'product_id'=>'1',
                'category_name'=>'Thuốc cần kê toa',
                'product_desc'=>'Không',
                'created_at'=>Carbon :: now()->format('Y-m-d H:i:s'),
                'created_at'=>Carbon :: now()->format('Y-m-d H:i:s'),
            ],
            [
                'product_id'=>'1',
                'category_name'=>'Cảnh Báo',
                'product_desc'=>'Phụ nữ có thai và cho con bú',
                'created_at'=>Carbon :: now()->format('Y-m-d H:i:s'),
                'created_at'=>Carbon :: now()->format('Y-m-d H:i:s'),
            ],
            
            
             [
                'product_id'=>'2',
                'category_name'=>'Thành Phần Chính',
                'product_desc'=>'Clopidogrel',
                'created_at'=>Carbon :: now()->format('Y-m-d H:i:s'),
                'created_at'=>Carbon :: now()->format('Y-m-d H:i:s'),
            ],
            [   
                'product_id'=>'2',
                'category_name'=>'Quy Cách',
                'product_desc'=>'Hộp 3 vỉ x 10 viên',
                'created_at'=>Carbon :: now()->format('Y-m-d H:i:s'),
                'created_at'=>Carbon :: now()->format('Y-m-d H:i:s'),
            ],
            [
                'product_id'=>'2',
                'category_name'=>'Xuất Xứ Thương Hiệu',
                'product_desc'=>'Việt Nam',
                'created_at'=>Carbon :: now()->format('Y-m-d H:i:s'),
                'created_at'=>Carbon :: now()->format('Y-m-d H:i:s'),
            ],
            [
                'product_id'=>'2',
                'category_name'=>'Dạng bào chế',
                'product_desc'=>'Viên nén',
                'created_at'=>Carbon :: now()->format('Y-m-d H:i:s'),
                'created_at'=>Carbon :: now()->format('Y-m-d H:i:s'),
            ],
            [
                'product_id'=>'2',
                'category_name'=>'Thuốc cần kê toa',
                'product_desc'=>'Có (Thuốc chỉ dùng theo đơn của bác sĩ)',
                'created_at'=>Carbon :: now()->format('Y-m-d H:i:s'),
                'created_at'=>Carbon :: now()->format('Y-m-d H:i:s'),
            ],
            [
                'product_id'=>'2',
                'category_name'=>'Cảnh Báo',
                'product_desc'=>'Phụ nữ có thai, Suy gan, Phụ nữ cho con bú',
                'created_at'=>Carbon :: now()->format('Y-m-d H:i:s'),
                'created_at'=>Carbon :: now()->format('Y-m-d H:i:s'),
            ],

            
            [
                'product_id'=>'3',
                'category_name'=>'Thành Phần Chính',
                'product_desc'=>' Amlodipine',
                'created_at'=>Carbon :: now()->format('Y-m-d H:i:s'),
                'created_at'=>Carbon :: now()->format('Y-m-d H:i:s'),
            ],
            [   
                'product_id'=>'3',
                'category_name'=>'Quy Cách',
                'product_desc'=>'Hộp 3 vỉ x 10 viên',
                'created_at'=>Carbon :: now()->format('Y-m-d H:i:s'),
                'created_at'=>Carbon :: now()->format('Y-m-d H:i:s'),
            ],
            [
                'product_id'=>'3',
                'category_name'=>'Xuất Xứ Thương Hiệu',
                'product_desc'=>'Hungary',
                'created_at'=>Carbon :: now()->format('Y-m-d H:i:s'),
                'created_at'=>Carbon :: now()->format('Y-m-d H:i:s'),
            ],
            [
                'product_id'=>'3',
                'category_name'=>'Dạng bào chế',
                'product_desc'=>'Viên nén',
                'created_at'=>Carbon :: now()->format('Y-m-d H:i:s'),
                'created_at'=>Carbon :: now()->format('Y-m-d H:i:s'),
            ],
            [
                'product_id'=>'3',
                'category_name'=>'Thuốc cần kê toa',
                'product_desc'=>'Có (Thuốc chỉ dùng theo đơn của bác sĩ)',
                'created_at'=>Carbon :: now()->format('Y-m-d H:i:s'),
                'created_at'=>Carbon :: now()->format('Y-m-d H:i:s'),
            ],
            [
                'product_id'=>'3',
                'category_name'=>'Cảnh Báo',
                'product_desc'=>'Lái tàu xe, Phụ nữ có thai',
                'created_at'=>Carbon :: now()->format('Y-m-d H:i:s'),
                'created_at'=>Carbon :: now()->format('Y-m-d H:i:s'),
            ],
            
            [
                'product_id'=>'4',
                'category_name'=>'Thành Phần Chính',
                'product_desc'=>'Ngưu tất (Rễ), Chỉ xác, Sài Hồ, Xích thược, Sinh Địa, Xuyên khung, Hồng hoa, Cam thảo',
                'created_at'=>Carbon :: now()->format('Y-m-d H:i:s'),
                'created_at'=>Carbon :: now()->format('Y-m-d H:i:s'),
            ],
            [   
                'product_id'=>'4',
                'category_name'=>'Quy Cách',
                'product_desc'=>'Hộp 3 vỉ x 10 viên',
                'created_at'=>Carbon :: now()->format('Y-m-d H:i:s'),
                'created_at'=>Carbon :: now()->format('Y-m-d H:i:s'),
            ],
            [
                'product_id'=>'4',
                'category_name'=>'Xuất Xứ Thương Hiệu',
                'product_desc'=>'Việt Nam',
                'created_at'=>Carbon :: now()->format('Y-m-d H:i:s'),
                'created_at'=>Carbon :: now()->format('Y-m-d H:i:s'),
            ],
            [
                'product_id'=>'4',
                'category_name'=>'Dạng bào chế',
                'product_desc'=>'Viên nang cứng',
                'created_at'=>Carbon :: now()->format('Y-m-d H:i:s'),
                'created_at'=>Carbon :: now()->format('Y-m-d H:i:s'),
            ],
            [
                'product_id'=>'4',
                'category_name'=>'Thuốc cần kê toa',
                'product_desc'=>'Không',
                'created_at'=>Carbon :: now()->format('Y-m-d H:i:s'),
                'created_at'=>Carbon :: now()->format('Y-m-d H:i:s'),
            ],
            [
                'product_id'=>'4',
                'category_name'=>'Cảnh Báo',
                'product_desc'=>'Phụ nữ có thai',
                'created_at'=>Carbon :: now()->format('Y-m-d H:i:s'),
                'created_at'=>Carbon :: now()->format('Y-m-d H:i:s'),
            ],
             [
                'product_id'=>'5',
                'category_name'=>'Thành Phần Chính',
                'product_desc'=>'Amlodipine',
                'created_at'=>Carbon :: now()->format('Y-m-d H:i:s'),
                'created_at'=>Carbon :: now()->format('Y-m-d H:i:s'),
            ],
            [   
                'product_id'=>'5',
                'category_name'=>'Quy Cách',
                'product_desc'=>'Hộp 3 vỉ x 10 viên',
                'created_at'=>Carbon :: now()->format('Y-m-d H:i:s'),
                'created_at'=>Carbon :: now()->format('Y-m-d H:i:s'),
            ],
            [
                'product_id'=>'5',
                'category_name'=>'Xuất Xứ Thương Hiệu',
                'product_desc'=>'Việt Nam',
                'created_at'=>Carbon :: now()->format('Y-m-d H:i:s'),
                'created_at'=>Carbon :: now()->format('Y-m-d H:i:s'),
            ],
            [
                'product_id'=>'5',
                'category_name'=>'Dạng bào chế',
                'product_desc'=>'Viên nang cứng',
                'created_at'=>Carbon :: now()->format('Y-m-d H:i:s'),
                'created_at'=>Carbon :: now()->format('Y-m-d H:i:s'),
            ],
            [
                'product_id'=>'5',
                'category_name'=>'Thuốc cần kê toa',
                'product_desc'=>'Có (Thuốc chỉ dùng theo đơn của bác sĩ)',
                'created_at'=>Carbon :: now()->format('Y-m-d H:i:s'),
                'created_at'=>Carbon :: now()->format('Y-m-d H:i:s'),
            ],
            [
                'product_id'=>'5',
                'category_name'=>'Cảnh Báo',
                'product_desc'=>'Phụ nữ có thai, Suy gan thận, Phụ nữ cho con bú',
                'created_at'=>Carbon :: now()->format('Y-m-d H:i:s'),
                'created_at'=>Carbon :: now()->format('Y-m-d H:i:s'),
            ],
            [
                'product_id'=>'6',
                'category_name'=>'Thành Phần Chính',
                'product_desc'=>'Ambroxol',
                'created_at'=>Carbon :: now()->format('Y-m-d H:i:s'),
                'created_at'=>Carbon :: now()->format('Y-m-d H:i:s'),
            ],
            [   
                'product_id'=>'6',
                'category_name'=>'Quy Cách',
                'product_desc'=>'Hộp 2 vỉ x 12 viên',
                'created_at'=>Carbon :: now()->format('Y-m-d H:i:s'),
                'created_at'=>Carbon :: now()->format('Y-m-d H:i:s'),
            ],
            [
                'product_id'=>'6',
                'category_name'=>'Xuất Xứ Thương Hiệu',
                'product_desc'=>'Anh',
                'created_at'=>Carbon :: now()->format('Y-m-d H:i:s'),
                'created_at'=>Carbon :: now()->format('Y-m-d H:i:s'),
            ],
            [
                'product_id'=>'6',
                'category_name'=>'Dạng bào chế',
                'product_desc'=>'Viên ngậm',
                'created_at'=>Carbon :: now()->format('Y-m-d H:i:s'),
                'created_at'=>Carbon :: now()->format('Y-m-d H:i:s'),
            ],
            [
                'product_id'=>'6',
                'category_name'=>'Thuốc cần kê toa',
                'product_desc'=>'Không',
                'created_at'=>Carbon :: now()->format('Y-m-d H:i:s'),
                'created_at'=>Carbon :: now()->format('Y-m-d H:i:s'),
            ],
            [
                'product_id'=>'6',
                'category_name'=>'Cảnh Báo',
                'product_desc'=>'Phụ nữ có thai',
                'created_at'=>Carbon :: now()->format('Y-m-d H:i:s'),
                'created_at'=>Carbon :: now()->format('Y-m-d H:i:s'),
            ],

            [
                'product_id'=>'7',
                'category_name'=>'Thành Phần Chính',
                'product_desc'=>'Amoxicillin, Clavulanic acid',
                'created_at'=>Carbon :: now()->format('Y-m-d H:i:s'),
                'created_at'=>Carbon :: now()->format('Y-m-d H:i:s'),
            ],
            [   
                'product_id'=>'7',
                'category_name'=>'Quy Cách',
                'product_desc'=>'Hộp 12 gói',
                'created_at'=>Carbon :: now()->format('Y-m-d H:i:s'),
                'created_at'=>Carbon :: now()->format('Y-m-d H:i:s'),
            ],
            [
                'product_id'=>'7',
                'category_name'=>'Xuất Xứ Thương Hiệu',
                'product_desc'=>'Việt Nam',
                'created_at'=>Carbon :: now()->format('Y-m-d H:i:s'),
                'created_at'=>Carbon :: now()->format('Y-m-d H:i:s'),
            ],
            [
                'product_id'=>'7',
                'category_name'=>'Dạng bào chế',
                'product_desc'=>'Dạng bột',
                'created_at'=>Carbon :: now()->format('Y-m-d H:i:s'),
                'created_at'=>Carbon :: now()->format('Y-m-d H:i:s'),
            ],
            [
                'product_id'=>'7',
                'category_name'=>'Thuốc cần kê toa',
                'product_desc'=>' Có (Thuốc chỉ dùng theo đơn của bác sĩ)',
                'created_at'=>Carbon :: now()->format('Y-m-d H:i:s'),
                'created_at'=>Carbon :: now()->format('Y-m-d H:i:s'),
            ],
            [
                'product_id'=>'7',
                'category_name'=>'Cảnh Báo',
                'product_desc'=>'Trẻ em, Người cao tuổi',
                'created_at'=>Carbon :: now()->format('Y-m-d H:i:s'),
                'created_at'=>Carbon :: now()->format('Y-m-d H:i:s'),
            ],
             [
                'product_id'=>'8',
                'category_name'=>'Thành Phần Chính',
                'product_desc'=>' Fexofenadine',
                'created_at'=>Carbon :: now()->format('Y-m-d H:i:s'),
                'created_at'=>Carbon :: now()->format('Y-m-d H:i:s'),
            ],
            [   
                'product_id'=>'8',
                'category_name'=>'Quy Cách',
                'product_desc'=>'Hộp 10 vỉ x 10 viên',
                'created_at'=>Carbon :: now()->format('Y-m-d H:i:s'),
                'created_at'=>Carbon :: now()->format('Y-m-d H:i:s'),
            ],
            [
                'product_id'=>'8',
                'category_name'=>'Xuất Xứ Thương Hiệu',
                'product_desc'=>'Việt Nam',
                'created_at'=>Carbon :: now()->format('Y-m-d H:i:s'),
                'created_at'=>Carbon :: now()->format('Y-m-d H:i:s'),
            ],
            [
                'product_id'=>'8',
                'category_name'=>'Dạng bào chế',
                'product_desc'=>'Viên nén bao phim',
                'created_at'=>Carbon :: now()->format('Y-m-d H:i:s'),
                'created_at'=>Carbon :: now()->format('Y-m-d H:i:s'),
            ],
            [
                'product_id'=>'8',
                'category_name'=>'Thuốc cần kê toa',
                'product_desc'=>'Không',
                'created_at'=>Carbon :: now()->format('Y-m-d H:i:s'),
                'created_at'=>Carbon :: now()->format('Y-m-d H:i:s'),
            ],
            [
                'product_id'=>'8',
                'category_name'=>'Cảnh Báo',
                'product_desc'=>'Trên 12 tuổi',
                'created_at'=>Carbon :: now()->format('Y-m-d H:i:s'),
                'created_at'=>Carbon :: now()->format('Y-m-d H:i:s'),
            ],
               [
                'product_id'=>'9',
                'category_name'=>'Thành Phần Chính',
                'product_desc'=>'Glucosamine, Tá dược vừa đủ',
                'created_at'=>Carbon :: now()->format('Y-m-d H:i:s'),
                'created_at'=>Carbon :: now()->format('Y-m-d H:i:s'),
            ],
            [   
                'product_id'=>'9',
                'category_name'=>'Quy Cách',
                'product_desc'=>'Hộp 30 gói x 4 g',
                'created_at'=>Carbon :: now()->format('Y-m-d H:i:s'),
                'created_at'=>Carbon :: now()->format('Y-m-d H:i:s'),
            ],
            [
                'product_id'=>'9',
                'category_name'=>'Xuất Xứ Thương Hiệu',
                'product_desc'=>'Đức',
                'created_at'=>Carbon :: now()->format('Y-m-d H:i:s'),
                'created_at'=>Carbon :: now()->format('Y-m-d H:i:s'),
            ],
            [
                'product_id'=>'9',
                'category_name'=>'Dạng bào chế',
                'product_desc'=>'Dạng bột',
                'created_at'=>Carbon :: now()->format('Y-m-d H:i:s'),
                'created_at'=>Carbon :: now()->format('Y-m-d H:i:s'),
            ],
            [
                'product_id'=>'9',
                'category_name'=>'Thuốc cần kê toa',
                'product_desc'=>' Không',
                'created_at'=>Carbon :: now()->format('Y-m-d H:i:s'),
                'created_at'=>Carbon :: now()->format('Y-m-d H:i:s'),
            ],
            [
                'product_id'=>'9',
                'category_name'=>'Cảnh Báo',
                'product_desc'=>' Người tiểu đường',
                'created_at'=>Carbon :: now()->format('Y-m-d H:i:s'),
                'created_at'=>Carbon :: now()->format('Y-m-d H:i:s'),
            ],
               [
                'product_id'=>'10',
                'category_name'=>'Thành Phần Chính',
                'product_desc'=>'Sắt',
                'created_at'=>Carbon :: now()->format('Y-m-d H:i:s'),
                'created_at'=>Carbon :: now()->format('Y-m-d H:i:s'),
            ],
            [   
                'product_id'=>'10',
                'category_name'=>'Quy Cách',
                'product_desc'=>'Hộp 20 ống',
                'created_at'=>Carbon :: now()->format('Y-m-d H:i:s'),
                'created_at'=>Carbon :: now()->format('Y-m-d H:i:s'),
            ],
            [
                'product_id'=>'10',
                'category_name'=>'Xuất Xứ Thương Hiệu',
                'product_desc'=>'Việt Nam',
                'created_at'=>Carbon :: now()->format('Y-m-d H:i:s'),
                'created_at'=>Carbon :: now()->format('Y-m-d H:i:s'),
            ],
            [
                'product_id'=>'10',
                'category_name'=>'Dạng bào chế',
                'product_desc'=>'Dung dịch',
                'created_at'=>Carbon :: now()->format('Y-m-d H:i:s'),
                'created_at'=>Carbon :: now()->format('Y-m-d H:i:s'),
            ],
            [
                'product_id'=>'10',
                'category_name'=>'Thuốc cần kê toa',
                'product_desc'=>' Không',
                'created_at'=>Carbon :: now()->format('Y-m-d H:i:s'),
                'created_at'=>Carbon :: now()->format('Y-m-d H:i:s'),
            ],
            [
                'product_id'=>'10',
                'category_name'=>'Cảnh Báo',
                'product_desc'=>'Trẻ em, Phụ nữ có thai, Phụ nữ cho con bú',
                'created_at'=>Carbon :: now()->format('Y-m-d H:i:s'),
                'created_at'=>Carbon :: now()->format('Y-m-d H:i:s'),
            ],
             [
                'product_id'=>'11',
                'category_name'=>'Thành Phần Chính',
                'product_desc'=>' Calci lactat, Canxi gluconat',
                'created_at'=>Carbon :: now()->format('Y-m-d H:i:s'),
                'created_at'=>Carbon :: now()->format('Y-m-d H:i:s'),
            ],
            [   
                'product_id'=>'11',
                'category_name'=>'Quy Cách',
                'product_desc'=>'Hộp 3 vỉ x 10 ống x 5ml',
                'created_at'=>Carbon :: now()->format('Y-m-d H:i:s'),
                'created_at'=>Carbon :: now()->format('Y-m-d H:i:s'),
            ],
            [
                'product_id'=>'11',
                'category_name'=>'Xuất Xứ Thương Hiệu',
                'product_desc'=>'Việt Nam',
                'created_at'=>Carbon :: now()->format('Y-m-d H:i:s'),
                'created_at'=>Carbon :: now()->format('Y-m-d H:i:s'),
            ],
            [
                'product_id'=>'11',
                'category_name'=>'Dạng bào chế',
                'product_desc'=>'Dung dịch',
                'created_at'=>Carbon :: now()->format('Y-m-d H:i:s'),
                'created_at'=>Carbon :: now()->format('Y-m-d H:i:s'),
            ],
            [
                'product_id'=>'11',
                'category_name'=>'Thuốc cần kê toa',
                'product_desc'=>' Không',
                'created_at'=>Carbon :: now()->format('Y-m-d H:i:s'),
                'created_at'=>Carbon :: now()->format('Y-m-d H:i:s'),
            ],
            [
                'product_id'=>'11',
                'category_name'=>'Cảnh Báo',
                'product_desc'=>'Trên 2 tuổi',
                'created_at'=>Carbon :: now()->format('Y-m-d H:i:s'),
                'created_at'=>Carbon :: now()->format('Y-m-d H:i:s'),
            ],
             [
                'product_id'=>'12',
                'category_name'=>'Thành Phần Chính',
                'product_desc'=>'Tolperisone',
                'created_at'=>Carbon :: now()->format('Y-m-d H:i:s'),
                'created_at'=>Carbon :: now()->format('Y-m-d H:i:s'),
            ],
            [   
                'product_id'=>'12',
                'category_name'=>'Quy Cách',
                'product_desc'=>'Hộp 3 vỉ x 10 viên',
                'created_at'=>Carbon :: now()->format('Y-m-d H:i:s'),
                'created_at'=>Carbon :: now()->format('Y-m-d H:i:s'),
            ],
            [
                'product_id'=>'12',
                'category_name'=>'Xuất Xứ Thương Hiệu',
                'product_desc'=>'Hungary',
                'created_at'=>Carbon :: now()->format('Y-m-d H:i:s'),
                'created_at'=>Carbon :: now()->format('Y-m-d H:i:s'),
            ],
            [
                'product_id'=>'12',
                'category_name'=>'Dạng bào chế',
                'product_desc'=>'Viên nén bao phim',
                'created_at'=>Carbon :: now()->format('Y-m-d H:i:s'),
                'created_at'=>Carbon :: now()->format('Y-m-d H:i:s'),
            ],
            [
                'product_id'=>'12',
                'category_name'=>'Thuốc cần kê toa',
                'product_desc'=>'Có (Thuốc chỉ dùng theo đơn của bác sĩ)',
                'created_at'=>Carbon :: now()->format('Y-m-d H:i:s'),
                'created_at'=>Carbon :: now()->format('Y-m-d H:i:s'),
            ],
            [
                'product_id'=>'12',
                'category_name'=>'Cảnh Báo',
                'product_desc'=>'Phụ nữ có thai, Phụ nữ cho con bú',
                'created_at'=>Carbon :: now()->format('Y-m-d H:i:s'),
                'created_at'=>Carbon :: now()->format('Y-m-d H:i:s'),
            ],
             [
                'product_id'=>'13',
                'category_name'=>'Thành Phần Chính',
                'product_desc'=>'Collagen cá',
                'created_at'=>Carbon :: now()->format('Y-m-d H:i:s'),
                'created_at'=>Carbon :: now()->format('Y-m-d H:i:s'),
            ],
            [   
                'product_id'=>'13',
                'category_name'=>'Quy Cách',
                'product_desc'=>'Hộp 60 viên',
                'created_at'=>Carbon :: now()->format('Y-m-d H:i:s'),
                'created_at'=>Carbon :: now()->format('Y-m-d H:i:s'),
            ],
            [
                'product_id'=>'13',
                'category_name'=>'Xuất Xứ Thương Hiệu',
                'product_desc'=>'Nhật Bản',
                'created_at'=>Carbon :: now()->format('Y-m-d H:i:s'),
                'created_at'=>Carbon :: now()->format('Y-m-d H:i:s'),
            ],
            [
                'product_id'=>'13',
                'category_name'=>'Dạng bào chế',
                'product_desc'=>'Viên nang cứng',
                'created_at'=>Carbon :: now()->format('Y-m-d H:i:s'),
                'created_at'=>Carbon :: now()->format('Y-m-d H:i:s'),
            ],
            [
                'product_id'=>'13',
                'category_name'=>'Thuốc cần kê toa',
                'product_desc'=>' Không',
                'created_at'=>Carbon :: now()->format('Y-m-d H:i:s'),
                'created_at'=>Carbon :: now()->format('Y-m-d H:i:s'),
            ],
            [
                'product_id'=>'13',
                'category_name'=>'Cảnh Báo',
                'product_desc'=>'Trẻ em, Phụ nữ có thai, Phụ nữ cho con bú',
                'created_at'=>Carbon :: now()->format('Y-m-d H:i:s'),
                'created_at'=>Carbon :: now()->format('Y-m-d H:i:s'),
            ],
             [
                'product_id'=>'14',
                'category_name'=>'Thành Phần Chính',
                'product_desc'=>'Glutathione, Collagen marin, Acid alpha lipoic',
                'created_at'=>Carbon :: now()->format('Y-m-d H:i:s'),
                'created_at'=>Carbon :: now()->format('Y-m-d H:i:s'),
            ],
            [   
                'product_id'=>'14',
                'category_name'=>'Quy Cách',
                'product_desc'=>'Hộp 60 viên',
                'created_at'=>Carbon :: now()->format('Y-m-d H:i:s'),
                'created_at'=>Carbon :: now()->format('Y-m-d H:i:s'),
            ],
            [
                'product_id'=>'14',
                'category_name'=>'Xuất Xứ Thương Hiệu',
                'product_desc'=>'Pháp',
                'created_at'=>Carbon :: now()->format('Y-m-d H:i:s'),
                'created_at'=>Carbon :: now()->format('Y-m-d H:i:s'),
            ],
            [
                'product_id'=>'14',
                'category_name'=>'Dạng bào chế',
                'product_desc'=>'Viên nang',
                'created_at'=>Carbon :: now()->format('Y-m-d H:i:s'),
                'created_at'=>Carbon :: now()->format('Y-m-d H:i:s'),
            ],
            [
                'product_id'=>'14',
                'category_name'=>'Thuốc cần kê toa',
                'product_desc'=>' Không',
                'created_at'=>Carbon :: now()->format('Y-m-d H:i:s'),
                'created_at'=>Carbon :: now()->format('Y-m-d H:i:s'),
            ],
            [
                'product_id'=>'14',
                'category_name'=>'Cảnh Báo',
                'product_desc'=>'Trẻ em, Phụ nữ có thai, Phụ nữ cho con bú',
                'created_at'=>Carbon :: now()->format('Y-m-d H:i:s'),
                'created_at'=>Carbon :: now()->format('Y-m-d H:i:s'),
            ],
            [
                'product_id'=>'15',
                'category_name'=>'Thành Phần Chính',
                'product_desc'=>'Chiết xuất quả lựu, Chùm ruột núi',
                'created_at'=>Carbon :: now()->format('Y-m-d H:i:s'),
                'created_at'=>Carbon :: now()->format('Y-m-d H:i:s'),
            ],
            [   
                'product_id'=>'15',
                'category_name'=>'Quy Cách',
                'product_desc'=>'Hộp 60 viên',
                'created_at'=>Carbon :: now()->format('Y-m-d H:i:s'),
                'created_at'=>Carbon :: now()->format('Y-m-d H:i:s'),
            ],
            [
                'product_id'=>'15',
                'category_name'=>'Xuất Xứ Thương Hiệu',
                'product_desc'=>'Thụy Điển',
                'created_at'=>Carbon :: now()->format('Y-m-d H:i:s'),
                'created_at'=>Carbon :: now()->format('Y-m-d H:i:s'),
            ],
            [
                'product_id'=>'15',
                'category_name'=>'Dạng bào chế',
                'product_desc'=>'Viên nén',
                'created_at'=>Carbon :: now()->format('Y-m-d H:i:s'),
                'created_at'=>Carbon :: now()->format('Y-m-d H:i:s'),
            ],
            [
                'product_id'=>'15',
                'category_name'=>'Thuốc cần kê toa',
                'product_desc'=>' Không',
                'created_at'=>Carbon :: now()->format('Y-m-d H:i:s'),
                'created_at'=>Carbon :: now()->format('Y-m-d H:i:s'),
            ],
            [
                'product_id'=>'15',
                'category_name'=>'Cảnh Báo',
                'product_desc'=>'Trẻ em, Phụ nữ có thai, Phụ nữ cho con bú',
                'created_at'=>Carbon :: now()->format('Y-m-d H:i:s'),
                'created_at'=>Carbon :: now()->format('Y-m-d H:i:s'),
            ],
            [
                'product_id'=>'16',
                'category_name'=>'Thành Phần Chính',
                'product_desc'=>'Nhân Sâm',
                'created_at'=>Carbon :: now()->format('Y-m-d H:i:s'),
                'created_at'=>Carbon :: now()->format('Y-m-d H:i:s'),
            ],
            [   
                'product_id'=>'16',
                'category_name'=>'Quy Cách',
                'product_desc'=>'Hộp 20 vỉ x 3 viên',
                'created_at'=>Carbon :: now()->format('Y-m-d H:i:s'),
                'created_at'=>Carbon :: now()->format('Y-m-d H:i:s'),
            ],
            [
                'product_id'=>'16',
                'category_name'=>'Xuất Xứ Thương Hiệu',
                'product_desc'=>'Việt Nam',
                'created_at'=>Carbon :: now()->format('Y-m-d H:i:s'),
                'created_at'=>Carbon :: now()->format('Y-m-d H:i:s'),
            ],
            [
                'product_id'=>'16',
                'category_name'=>'Dạng bào chế',
                'product_desc'=>'Viên nang mềm',
                'created_at'=>Carbon :: now()->format('Y-m-d H:i:s'),
                'created_at'=>Carbon :: now()->format('Y-m-d H:i:s'),
            ],
            [
                'product_id'=>'16',
                'category_name'=>'Thuốc cần kê toa',
                'product_desc'=>' Không',
                'created_at'=>Carbon :: now()->format('Y-m-d H:i:s'),
                'created_at'=>Carbon :: now()->format('Y-m-d H:i:s'),
            ],
            [
                'product_id'=>'16',
                'category_name'=>'Cảnh Báo',
                'product_desc'=>'Trẻ em, Phụ nữ có thai, Phụ nữ cho con bú',
                'created_at'=>Carbon :: now()->format('Y-m-d H:i:s'),
                'created_at'=>Carbon :: now()->format('Y-m-d H:i:s'),
            ],
            [
                'product_id'=>'17',
                'category_name'=>'Thành Phần Chính',
                'product_desc'=>'Ginkgo biloba',
                'created_at'=>Carbon :: now()->format('Y-m-d H:i:s'),
                'created_at'=>Carbon :: now()->format('Y-m-d H:i:s'),
            ],
            [   
                'product_id'=>'17',
                'category_name'=>'Quy Cách',
                'product_desc'=>'Hộp 30 viên',
                'created_at'=>Carbon :: now()->format('Y-m-d H:i:s'),
                'created_at'=>Carbon :: now()->format('Y-m-d H:i:s'),
            ],
            [
                'product_id'=>'17',
                'category_name'=>'Xuất Xứ Thương Hiệu',
                'product_desc'=>'Việt Nam',
                'created_at'=>Carbon :: now()->format('Y-m-d H:i:s'),
                'created_at'=>Carbon :: now()->format('Y-m-d H:i:s'),
            ],
            [
                'product_id'=>'17',
                'category_name'=>'Dạng bào chế',
                'product_desc'=>'Viên nén',
                'created_at'=>Carbon :: now()->format('Y-m-d H:i:s'),
                'created_at'=>Carbon :: now()->format('Y-m-d H:i:s'),
            ],
            [
                'product_id'=>'17',
                'category_name'=>'Thuốc cần kê toa',
                'product_desc'=>' Không',
                'created_at'=>Carbon :: now()->format('Y-m-d H:i:s'),
                'created_at'=>Carbon :: now()->format('Y-m-d H:i:s'),
            ],
            [
                'product_id'=>'17',
                'category_name'=>'Cảnh Báo',
                'product_desc'=>'Trẻ em, Phụ nữ có thai, Phụ nữ cho con bú',
                'created_at'=>Carbon :: now()->format('Y-m-d H:i:s'),
                'created_at'=>Carbon :: now()->format('Y-m-d H:i:s'),
            ],
            [
                'product_id'=>'18',
                'category_name'=>'Thành Phần Chính',
                'product_desc'=>'Glucosamine sulphate, Calci carbonate nano',
                'created_at'=>Carbon :: now()->format('Y-m-d H:i:s'),
                'created_at'=>Carbon :: now()->format('Y-m-d H:i:s'),
            ],
            [   
                'product_id'=>'18',
                'category_name'=>'Quy Cách',
                'product_desc'=>'Hộp 100 viên',
                'created_at'=>Carbon :: now()->format('Y-m-d H:i:s'),
                'created_at'=>Carbon :: now()->format('Y-m-d H:i:s'),
            ],
            [
                'product_id'=>'18',
                'category_name'=>'Xuất Xứ Thương Hiệu',
                'product_desc'=>'Pháp',
                'created_at'=>Carbon :: now()->format('Y-m-d H:i:s'),
                'created_at'=>Carbon :: now()->format('Y-m-d H:i:s'),
            ],
            [
                'product_id'=>'18',
                'category_name'=>'Dạng bào chế',
                'product_desc'=>'Viên nén',
                'created_at'=>Carbon :: now()->format('Y-m-d H:i:s'),
                'created_at'=>Carbon :: now()->format('Y-m-d H:i:s'),
            ],
            [
                'product_id'=>'18',
                'category_name'=>'Thuốc cần kê toa',
                'product_desc'=>' Không',
                'created_at'=>Carbon :: now()->format('Y-m-d H:i:s'),
                'created_at'=>Carbon :: now()->format('Y-m-d H:i:s'),
            ],
            [
                'product_id'=>'18',
                'category_name'=>'Cảnh Báo',
                'product_desc'=>'Trẻ em, Phụ nữ có thai, Phụ nữ cho con bú',
                'created_at'=>Carbon :: now()->format('Y-m-d H:i:s'),
                'created_at'=>Carbon :: now()->format('Y-m-d H:i:s'),
            ],
            [
                'product_id'=>'19',
                'category_name'=>'Thành Phần Chính',
                'product_desc'=>'Calcium Carbonate',
                'created_at'=>Carbon :: now()->format('Y-m-d H:i:s'),
                'created_at'=>Carbon :: now()->format('Y-m-d H:i:s'),
            ],
            [   
                'product_id'=>'19',
                'category_name'=>'Quy Cách',
                'product_desc'=>'Hộp 60 viên',
                'created_at'=>Carbon :: now()->format('Y-m-d H:i:s'),
                'created_at'=>Carbon :: now()->format('Y-m-d H:i:s'),
            ],
            [
                'product_id'=>'19',
                'category_name'=>'Xuất Xứ Thương Hiệu',
                'product_desc'=>'Pháp',
                'created_at'=>Carbon :: now()->format('Y-m-d H:i:s'),
                'created_at'=>Carbon :: now()->format('Y-m-d H:i:s'),
            ],
            [
                'product_id'=>'19',
                'category_name'=>'Dạng bào chế',
                'product_desc'=>'Viên nang',
                'created_at'=>Carbon :: now()->format('Y-m-d H:i:s'),
                'created_at'=>Carbon :: now()->format('Y-m-d H:i:s'),
            ],
            [
                'product_id'=>'19',
                'category_name'=>'Thuốc cần kê toa',
                'product_desc'=>' Không',
                'created_at'=>Carbon :: now()->format('Y-m-d H:i:s'),
                'created_at'=>Carbon :: now()->format('Y-m-d H:i:s'),
            ],
            [
                'product_id'=>'19',
                'category_name'=>'Cảnh Báo',
                'product_desc'=>'Trẻ em, Phụ nữ có thai, Phụ nữ cho con bú',
                'created_at'=>Carbon :: now()->format('Y-m-d H:i:s'),
                'created_at'=>Carbon :: now()->format('Y-m-d H:i:s'),
            ],
            [
                'product_id'=>'20',
                'category_name'=>'Thành Phần Chính',
                'product_desc'=>'Calcium',
                'created_at'=>Carbon :: now()->format('Y-m-d H:i:s'),
                'created_at'=>Carbon :: now()->format('Y-m-d H:i:s'),
            ],
            [   
                'product_id'=>'20',
                'category_name'=>'Quy Cách',
                'product_desc'=>'Hộp 3 vỉ x 10 viên',
                'created_at'=>Carbon :: now()->format('Y-m-d H:i:s'),
                'created_at'=>Carbon :: now()->format('Y-m-d H:i:s'),
            ],
            [
                'product_id'=>'20',
                'category_name'=>'Xuất Xứ Thương Hiệu',
                'product_desc'=>'Hoa Kỳ',
                'created_at'=>Carbon :: now()->format('Y-m-d H:i:s'),
                'created_at'=>Carbon :: now()->format('Y-m-d H:i:s'),
            ],
            [
                'product_id'=>'20',
                'category_name'=>'Dạng bào chế',
                'product_desc'=>'Viên nang mềm',
                'created_at'=>Carbon :: now()->format('Y-m-d H:i:s'),
                'created_at'=>Carbon :: now()->format('Y-m-d H:i:s'),
            ],
            [
                'product_id'=>'20',
                'category_name'=>'Thuốc cần kê toa',
                'product_desc'=>' Không',
                'created_at'=>Carbon :: now()->format('Y-m-d H:i:s'),
                'created_at'=>Carbon :: now()->format('Y-m-d H:i:s'),
            ],
            [
                'product_id'=>'20',
                'category_name'=>'Cảnh Báo',
                'product_desc'=>'Trẻ em, Phụ nữ có thai, Phụ nữ cho con bú',
                'created_at'=>Carbon :: now()->format('Y-m-d H:i:s'),
                'created_at'=>Carbon :: now()->format('Y-m-d H:i:s'),
            ],
            [
                'product_id'=>'21',
                'category_name'=>'Thành Phần',
                'product_desc'=>'Vải không dệt PP, Vải bông, giấy kháng khuẩn MELTBLOWN, Thanh nẹp mũi bằng nhựa, Dây đeo có tính đàn hồ',
                'created_at'=>Carbon :: now()->format('Y-m-d H:i:s'),
                'created_at'=>Carbon :: now()->format('Y-m-d H:i:s'),
            ],
            [
                'product_id'=>'21',
                'category_name'=>'Xuất Xứ',
                'product_desc'=>'Việt Nam',
                'created_at'=>Carbon :: now()->format('Y-m-d H:i:s'),
                'created_at'=>Carbon :: now()->format('Y-m-d H:i:s'),
            ],
              [
                'product_id'=>'21',
                'category_name'=>'Màu Sắc',
                'product_desc'=>'Trắng',
                'created_at'=>Carbon :: now()->format('Y-m-d H:i:s'),
                'created_at'=>Carbon :: now()->format('Y-m-d H:i:s'),
            ],
              [
                'product_id'=>'21',
                'category_name'=>'Công Dụng',
                'product_desc'=>'Khẩu Trang Hamita N95 được thiết kế để bảo vệ sức khỏe cộng đồng. Ngăn ngừa sự xâm nhập của vi khuẩn, bụi, khói, giọt bắn...',
                'created_at'=>Carbon :: now()->format('Y-m-d H:i:s'),
                'created_at'=>Carbon :: now()->format('Y-m-d H:i:s'),
            ],
            [
                'product_id'=>'22',
                'category_name'=>'Thành Phần',
                'product_desc'=>'Vải không dệt công nghệ mới, siêu mềm mịn,Lớp màng lọc',
                'created_at'=>Carbon :: now()->format('Y-m-d H:i:s'),
                'created_at'=>Carbon :: now()->format('Y-m-d H:i:s'),
            ],
            [
                'product_id'=>'22',
                'category_name'=>'Xuất Xứ',
                'product_desc'=>'Việt Nam',
                'created_at'=>Carbon :: now()->format('Y-m-d H:i:s'),
                'created_at'=>Carbon :: now()->format('Y-m-d H:i:s'),
            ],
                [
                'product_id'=>'22',
                'category_name'=>'Màu Sắc',
                'product_desc'=>'Trắng',
                'created_at'=>Carbon :: now()->format('Y-m-d H:i:s'),
                'created_at'=>Carbon :: now()->format('Y-m-d H:i:s'),
            ],
             [
                'product_id'=>'22',
                'category_name'=>'Công Dụng',
                'product_desc'=>'Khẩu Trang Y Tế Cao Cấp Vĩnh Tiến Kn95 3Hmask 12C được sản xuất bằng công nghệ hiện đại, kháng khuẩn đến 99%, dễ dàng hít thở và không gây dị ứng cho người sử dụng.',
                'created_at'=>Carbon :: now()->format('Y-m-d H:i:s'),
                'created_at'=>Carbon :: now()->format('Y-m-d H:i:s'),
            ],
            [
                'product_id'=>'23',
                'category_name'=>'Thành Phần',
                'product_desc'=>'Vải không dệt PP, giấy kháng khuẩn MELTBLOWN, Vải kháng khuẩn SMS',
                'created_at'=>Carbon :: now()->format('Y-m-d H:i:s'),
                'created_at'=>Carbon :: now()->format('Y-m-d H:i:s'),
            ],
             [
                'product_id'=>'23',
                'category_name'=>'Xuất Xứ',
                'product_desc'=>'Việt Nam',
                'created_at'=>Carbon :: now()->format('Y-m-d H:i:s'),
                'created_at'=>Carbon :: now()->format('Y-m-d H:i:s'),
             ],
            [
                'product_id'=>'23',
                'category_name'=>'Màu Sắc',
                'product_desc'=>'Trắng',
                'created_at'=>Carbon :: now()->format('Y-m-d H:i:s'),
                'created_at'=>Carbon :: now()->format('Y-m-d H:i:s'),
            ],
            [
                'product_id'=>'23',
                'category_name'=>'Công Dụng',
                'product_desc'=>'Khẩu trang y tế người lớn Hamita Advanced 4D Mask có khả năng bảo vệ chống nhiễm khuẩn đến 99.60%, thiết kế 4D thông minh ôm khít khuôn mặt, giúp bảo vệ hiệu quả khỏi khói bụi ô nhiễm, chống giọt bắn và vi khuẩn từ môi trường.',
                'created_at'=>Carbon :: now()->format('Y-m-d H:i:s'),
                'created_at'=>Carbon :: now()->format('Y-m-d H:i:s'),
            ],
            [
                'product_id'=>'24',
                'category_name'=>'Quy Cách',
                'product_desc'=>'Hộp 1 Cái',
                'created_at'=>Carbon :: now()->format('Y-m-d H:i:s'),
                'created_at'=>Carbon :: now()->format('Y-m-d H:i:s'),
            ],
            [
                'product_id'=>'24',
                'category_name'=>'Xuất Xứ',
                'product_desc'=>'Đức',
                'created_at'=>Carbon :: now()->format('Y-m-d H:i:s'),
                'created_at'=>Carbon :: now()->format('Y-m-d H:i:s'),
             ],
             [
                'product_id'=>'24',
                'category_name'=>'Màu Sắc',
                'product_desc'=>'Trắng',
                'created_at'=>Carbon :: now()->format('Y-m-d H:i:s'),
                'created_at'=>Carbon :: now()->format('Y-m-d H:i:s'),
            ],
              [
                'product_id'=>'24',
                'category_name'=>'Công Dụng',
                'product_desc'=>'Nhiệt Kế Đầu Mềm Beurer Ft15 giúp đo nhiệt độ nhanh trong khoảng 10 giây, đầu đo mềm, linh hoạt, an toàn với trẻ nhỏ. Thiết bị có các chức năng nổi bật như: Phát tín hiệu âm thanh báo kết quả đo, cảnh báo sốt, tự động tắt, không thấm nước,...',
                'created_at'=>Carbon :: now()->format('Y-m-d H:i:s'),
                'created_at'=>Carbon :: now()->format('Y-m-d H:i:s'),
            ],
              [
                'product_id'=>'25',
                'category_name'=>'Thành Phần',
                'product_desc'=>' Sorbitol, Hydrated silica, Flavor, Cellulose gum, Sodium fluoride, Sodium saccharin, Troxerutin, Water Sodium Chloride, PEG-32, Xylitol Sodium Lauryl Sulfat, Psidium Guajava Fruit, Propolis Extract, Mica',
                'created_at'=>Carbon :: now()->format('Y-m-d H:i:s'),
                'created_at'=>Carbon :: now()->format('Y-m-d H:i:s'),
            ],
               [
                'product_id'=>'25',
                'category_name'=>'Quy Cách',
                'product_desc'=>'tuýp 95g',
                'created_at'=>Carbon :: now()->format('Y-m-d H:i:s'),
                'created_at'=>Carbon :: now()->format('Y-m-d H:i:s'),
            ],
            [
                'product_id'=>'25',
                'category_name'=>'Xuất Xứ',
                'product_desc'=>'Việt Nam',
                'created_at'=>Carbon :: now()->format('Y-m-d H:i:s'),
                'created_at'=>Carbon :: now()->format('Y-m-d H:i:s'),
            ],
               [
                'product_id'=>'25',
                'category_name'=>'Công Dụng',
                'product_desc'=>'Lipzo Gum Protect là sự kết hợp giữa Xylitol, tính chất muối biển',
                'created_at'=>Carbon :: now()->format('Y-m-d H:i:s'),
                'created_at'=>Carbon :: now()->format('Y-m-d H:i:s'),
            ],
             [
                'product_id'=>'26',
                'category_name'=>'Thành Phần',
                'product_desc'=>'Hồng sâm, Nhung hươu, Táo đỏ, Câu kỷ tử, Nước cất, Fructooligosaccharides, Quế, Gừng, Linh chi',
                'created_at'=>Carbon :: now()->format('Y-m-d H:i:s'),
                'created_at'=>Carbon :: now()->format('Y-m-d H:i:s'),
            ],
               [
                'product_id'=>'26',
                'category_name'=>'Quy Cách',
                'product_desc'=>'Hộp 50 Viên',
                'created_at'=>Carbon :: now()->format('Y-m-d H:i:s'),
                'created_at'=>Carbon :: now()->format('Y-m-d H:i:s'),
            ],
            [
                'product_id'=>'26',
                'category_name'=>'Xuất Xứ',
                'product_desc'=>'Hàn Quốc',
                'created_at'=>Carbon :: now()->format('Y-m-d H:i:s'),
                'created_at'=>Carbon :: now()->format('Y-m-d H:i:s'),
            ],
               [
                'product_id'=>'26',
                'category_name'=>'Công Dụng',
                'product_desc'=>'Nước Hồng Sâm Hongsamjin Plus là sản phẩm kết hợp các thành phần cao cấp, quý hiếm như chiết xuất Hồng sâm Hàn Quốc 6 năm tuổi, Gạc Hươu, Linh Chi, Nhung Hươu, Táo đỏ và Câu Kỷ Tử mang đến giá trị dinh dưỡng',
                'created_at'=>Carbon :: now()->format('Y-m-d H:i:s'),
                'created_at'=>Carbon :: now()->format('Y-m-d H:i:s'),
            ],
            [
                'product_id'=>'27',
                'category_name'=>'Thành Phần',
                'product_desc'=>' Curcumin, Mật ong, Sữa ong chúa',
                'created_at'=>Carbon :: now()->format('Y-m-d H:i:s'),
                'created_at'=>Carbon :: now()->format('Y-m-d H:i:s'),
            ],
               [
                'product_id'=>'27',
                'category_name'=>'Nhà Sản Xuất',
                'product_desc'=>'Công Ty Cổ Phần Ong Mật Tiền Giang',
                'created_at'=>Carbon :: now()->format('Y-m-d H:i:s'),
                'created_at'=>Carbon :: now()->format('Y-m-d H:i:s'),
            ],
            [
                'product_id'=>'27',
                'category_name'=>'Xuất Xứ',
                'product_desc'=>'Việt Nam',
                'created_at'=>Carbon :: now()->format('Y-m-d H:i:s'),
                'created_at'=>Carbon :: now()->format('Y-m-d H:i:s'),
            ],
               [
                'product_id'=>'27',
                'category_name'=>'Công Dụng',
                'product_desc'=>'Viên tinh nghệ mật sữa chúa là sự kết hợp hoàn hảo của sữa ong chúa tươi, mật ong và tinh nghệ Curcumin tạo ra 1 sản phẩm chất lượng có mùi vị thơm ngon, tiện lợi khi sử dụng và tốt cho sức khỏe.',
                'created_at'=>Carbon :: now()->format('Y-m-d H:i:s'),
                'created_at'=>Carbon :: now()->format('Y-m-d H:i:s'),
            ],
            [
                'product_id'=>'28',
                'category_name'=>'Mùi Hương',
                'product_desc'=>' Hương trà xanh, Hương Chanh, Hương sả',
                'created_at'=>Carbon :: now()->format('Y-m-d H:i:s'),
                'created_at'=>Carbon :: now()->format('Y-m-d H:i:s'),
            ],
               [
                'product_id'=>'28',
                'category_name'=>'Nhà Sản Xuất',
                'product_desc'=>'Lavita',
                'created_at'=>Carbon :: now()->format('Y-m-d H:i:s'),
                'created_at'=>Carbon :: now()->format('Y-m-d H:i:s'),
            ],
            [
                'product_id'=>'28',
                'category_name'=>'Xuất Xứ',
                'product_desc'=>'Việt Nam',
                'created_at'=>Carbon :: now()->format('Y-m-d H:i:s'),
                'created_at'=>Carbon :: now()->format('Y-m-d H:i:s'),
            ],
               [
                'product_id'=>'28',
                'category_name'=>'Công Dụng',
                'product_desc'=>'Dung dịch rửa tay khô Natural Hand Sanitizer là sản phẩm giúp làm sạch và loại bỏ hầu hết vi khuẩn gây hại trên da tay.',
                'created_at'=>Carbon :: now()->format('Y-m-d H:i:s'),
                'created_at'=>Carbon :: now()->format('Y-m-d H:i:s'),
            ],
            [
                'product_id'=>'29',
                'category_name'=>'Thành Phần',
                'product_desc'=>'  Water, Hydrated silica, Sorbitol, Glycerin, Peg-8, Flavor, Titanium dioxide, Cocamidopropyl betaine, Xanthan gum, Sodium hydroxide, Sodium',
                'created_at'=>Carbon :: now()->format('Y-m-d H:i:s'),
                'created_at'=>Carbon :: now()->format('Y-m-d H:i:s'),
            ],
               [
                'product_id'=>'29',
                'category_name'=>'Quy Cách',
                'product_desc'=>'Tuýp 100ml',
                'created_at'=>Carbon :: now()->format('Y-m-d H:i:s'),
                'created_at'=>Carbon :: now()->format('Y-m-d H:i:s'),
            ],
            [
                'product_id'=>'29',
                'category_name'=>'Xuất Xứ',
                'product_desc'=>'Việt Nam',
                'created_at'=>Carbon :: now()->format('Y-m-d H:i:s'),
                'created_at'=>Carbon :: now()->format('Y-m-d H:i:s'),
            ],
               [
                'product_id'=>'29',
                'category_name'=>'Công Dụng',
                'product_desc'=>'Kem đánh răng Dental Sensitive Whitening Formula giúp cải thiện tình trạng ê buốt, ',
                'created_at'=>Carbon :: now()->format('Y-m-d H:i:s'),
                'created_at'=>Carbon :: now()->format('Y-m-d H:i:s'),
            ],
        ]);
    }
    
}
